const WeatherActionTypes = {
    FETCH_WEATHER_START: 'FETCH_WEATHER_START',
    FETCH_WEATHER_SUCCESS: 'FETCH_WEATHER_SUCCESS',
    FETCH_WEATHER_FAILURE: 'FETCH_WEATHER_FAILURE',
}

export default WeatherActionTypes;